[package]
name = "convert-jisx0208-to-unicode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdf = "0.6.0"
csv = "1.2.0"
regex = "1.7.1"
